version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: image-editor-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  php-apache:
    container_name: php-apache
    build:
      context: ./api/docker/php
    ports:
      - 8080:80
    volumes:
      - ./api/:/var/www/html
      - ./api/docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database
